### ISSUE TITLE
redux-first-router

### ISSUE THREAD

**Issue by romseguy** [cjdev/routedux#1]
For inspiration https://github.com/faceyspacey/redux-first-router

**Comment by msumme** [comment]
What specifically do you think we should emulate?

We discovered that library slightly after finishing our own, but the limitation only one route per action wouldn't work for some of our use cases.  

We have been working on determining which features might make this more useful to the community at large while at the same time avoiding making it a kitchen-sink library that tries to do too much.

**Comment by romseguy** [comment]
I don't think you should emulate anything, it's probably best to have a router like routedux with a minimal surface API for people building client-only apps. Then if they need server side rendering they could switch to redux-first-router. That way both libraries would complement each other.

Also, here's an argument (from RFR author) against removing route matching components (I had a quick look and it seems you've implemented fragments)

https://medium.com/faceyspacey/pre-release-redux-first-router-a-step-beyond-redux-little-router-cd2716576aea
> As far as Redux developers are concerned, using <Route/> or <Fragment/> is a carry-over from the bygone era of React Router. Route-matching components make a whole lot of sense when you have nothing else to make decisions based on. But you do.
> Conditionally rendering based on both kinds of state (URL + regular Redux state) is still not solved by <Fragment/>. For example: if you want to show something if the URL is /users and you have your users fetched + stored in Redux.
> And it’s not very informational compared to the infinite custom logic you can come up with in your reducers.
> The realization is that — if used to the fullest, which we’ll get to soon — a global reactive state tree completely replaces the need for route-matching components like <Route/> in React Router or <Fragment/> in redux-little-router.

**Comment by msumme** [comment]
Our "Fragment" doesn't use routes for filtering at all.  We actually only created it as a convenience to show/hide parts of your application based on state.  If you look at the implementation, it's just a simple path lookup through the store.

 We don't even store the url in the store or provide an easy mechanism to do so.

I don't know that our library actually couldn't handle server-side rendering - we just haven't tried it since it wasn't a use-case for us at the time.  What makes you think it wouldn't work?

**Comment by msumme** [comment]
The real reason we introduced <Fragment /> was to provide some basic familiarity to people coming from redux-little-router or react-router so they could see how you would accomplish the same kind of hiding pats of your application. 

But our examples show it's just a function of state, instead of a function of url path.
